# -*- coding: utf-8 -*-
"""Simple Car game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-KvV3d-49IXOfBaG0CWAaOf_XRIugVsk
"""

command = ""
started = False
while True:
  command = input('>').lower()
  if command == "start":
    if started:
      print("Car has already started")
    else:
      started = True
      print("Car starts...")
  elif command == "stop":
    if not started:
      print("Car has already stopped")
    else:
      started = False
      print("Car stops...")
  elif command == "help":
    print('''
start - to start the car
stop - to stop the car
quit - to exit''')
  elif command == "quit":
    break
  else:
    print("I don't understand the command")